services:
  solarpanel:
    image: ovitor/solarpanel:latest
    container_name: solarpanel
    restart: unless-stopped
    ports:
      - "18080:18080"
      - "18443:18443"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - HTTPS_PORT=18443
